### ISSUE TITLE
Blender 2.79b - Blender CTD after Render Shading preview

### ISSUE THREAD

**Issue by Gnates** [johnzero7/XNALaraMesh#25]
Blender 2.79b 64bit

After **importing** a XPS model, **converting materials to Cycles**, and then switching **Viewport Shading** to **Rendered**, Blender crashes to desktop.
- https://gfycat.com/DeepKaleidoscopicLarva

This happened with only 1 model:
- https://www.deviantart.com/mjump/art/Soul-Calibur-2-Ivy-332527666

**Comment by johnzero7** [comment]
I was able to reproduce and find the cause of the crash.
Unfortunately is and issue that blender 2.79b as with some .dds textures in cycles. For example texture for the gem on the right hand (Ivy_0028.dds). 
You can even apply this texture to the default cube and it will crash cycles.

Since the Blender devs are devoting all their time to 2.80 I don't think they will ever address this issue.

The only solution you have is to manually convert the texture causing this problem to another format (PNG, TGA, JPG, etc.) and replace the texture in the model.

**Comment by Gnates** [comment]
Thank you. Hopefully this will be fixed in Blender 2.8.
