### ISSUE TITLE
Blender 2.8 : Export not working

### ISSUE THREAD

**Issue by ihatzi** [johnzero7/XNALaraMesh#51]
If I import an XPS model into blender 2.8, then immediately export to OBJ, the new obj file looses all its textures

Also, if I import an XPS model into 2.8, then export to XPS, the new XPS file also has no textures

The 2.7x version seems to work properly, think it is a 2.8 specific issue.

**Comment by johnzero7** [comment]
That is a new "feature" of Blender 2.80.

In 2.79 you had Blender internal, and you could mark each texture as "Color", "Ambient", "Emit", etc.
But in 2.80 Bender Internal is gone ( F ), you only have node materials for cycles and eevee. Nodes are great because you can make really crazy and awesome things, the downside is that it becomes difficult for exporter to export the materials. That is an issue that all exporters in Blender currently have. 

For .xps and .mesh you need to recreate the material in XPS using the material editor (shortcut Ctrl+T).
