### ISSUE TITLE
Name Collection after the file

### ISSUE THREAD

**Issue by CastelHQ** [johnzero7/XNALaraMesh#52]
Hello, I looked through Issues and saw that naming imported objects after their respective files is not a desired way by the developer. But it still can be quite tedious to rename every object when working with a lot of files. 
So I wanna propose a compromise, so to speak. Instead of renaming objects, which can be problematic as per the developer, the add-on should name the collection it creates after the file that was imported.
I hope this solution is compelling enough as it would've helped me A LOT.
P.S. To be clear this is a feature request, since I'm not a coder/developer. Thanks!

**Comment by johnzero7** [comment]
Currently all models are imported as collections named "XPS Model", "XPS Model.001", "XPS Model.002" and so on.
I could make the collection to be named as the imported file, but that would not be much help since all XPS models are named "generic_item.mesh" or "xps.xps". There is no name for the model inside the file neither.
So there is not any good solution for this small issue.

**Comment by CastelHQ** [comment]
Yeah, I guess it's doesn't make much sense for general XPS use. My case is not a common one I guess. 150+ face blend shapes per character - all exported as separate .mesh.ascii files (e.g. smile_l.mesh.ascii). Importing them one by one and renaming to keep track which is which is a pain. I guess I'll just have to brute force through it...
Thanks for your time anyways

**Comment by johnzero7** [comment]
Just changed the behavior of collection creation, now the new collection is created inside the active collection (issue #53). While at it included decided also change the collection name to use the file name. No big difference for most users, but useful in the case (very odd case) you described. Enjoy.
